# Generated by Django 5.2.8 on 2025-11-30 09:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('topic', 'Specific Topic Series'), ('bio', 'General Brand Awareness')], max_length=20)),
                ('topic_prompt', models.TextField(blank=True)),
                ('posts_per_day', models.IntegerField(default=3)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('daily_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('interval_hours', models.IntegerField(default=2)),
                ('auto_approve', models.BooleanField(default=False, help_text='If checked, posts will be published without your review.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_pool/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_bio', models.TextField()),
                ('instagram_access_token', models.CharField(max_length=500)),
                ('instagram_business_id', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_update', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('scheduled_time', models.DateTimeField()),
                ('requires_approval', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled (Waiting for AI)'), ('generating', 'Generating AI...'), ('waiting_approval', 'AI Done (Needs Review)'), ('approved', 'Approved (Queue to Post)'), ('publishing', 'Publishing in Progress...'), ('posted', 'Posted'), ('error', 'Error')], default='draft', max_length=20)),
                ('generated_caption', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
